version: '3.8'

services:
  rabbitmq-1:
    image: rabbitmq:3.11-management
    ports:
      - "15672:15672"
      - "5671:5671"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/certs:/etc/rabbitmq/certs
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  camera-node-1:
    build: ./servicios/nodoCamara
    environment:
      # Estas variables apuntan a rutas DENTRO del contenedor, por eso el volumen es necesario
      - RABBITMQ_HOST=rabbitmq-1
      - RABBITMQ_PORT=5671
      - CA_CERT=/etc/rabbitmq/certs/ca_certificate.pem
      - CLIENT_CERT=/etc/rabbitmq/certs/client_certificate.pem
      - CLIENT_KEY=/etc/rabbitmq/certs/client_key.pem
      - CAMERA_INDEX=0
    volumes:
      # >> ¡CAMBIO CLAVE! Añadir este volumen para que el cliente pueda encontrar los certificados
      - ./rabbitmq:/etc/rabbitmq
    devices:
      - "/dev/video0:/dev/video0"
    depends_on:
      rabbitmq-1:
        condition: service_healthy

  processing-node-1:
    build: ./servicios/nodoProcesamiento
    environment:
      # Estas variables apuntan a rutas DENTRO del contenedor, por eso el volumen es necesario
      - RABBITMQ_HOST=rabbitmq-1
      - RABBITMQ_PORT=5671
      - CA_CERT=/etc/rabbitmq/certs/ca_certificate.pem
      - CLIENT_CERT=/etc/rabbitmq/certs/client_certificate.pem
      - CLIENT_KEY=/etc/rabbitmq/certs/client_key.pem
      - GDK_BACKEND=x11
      - QT_QPA_PLATFORM=xcb
      - DISPLAY=:0
      - YOLO_CONFIG_DIR=/app/config # Opcional: para el warning de Ultralytics
    volumes:
      # >> ¡CAMBIO CLAVE! Añadir este volumen para que el cliente pueda encontrar los certificados
      - ./rabbitmq:/etc/rabbitmq
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      rabbitmq-1:
        condition: service_healthy